### ISSUE TITLE
GPIO development (LED + Buzzer + Push button)

### ISSUE THREAD

**Issue by charan1811** [JayashCUB/final-project-assignment-Intelligent_Driver_Assistance_and_Parking_System#14]
Description:
Develop GPIO to integrate led and buzzer functionality. Testing push button.

DoD:
Successfully integrate and test if the led, Buzzer and push button is working.

Blockers:
None

**Comment by JayashCUB** [comment]
**Task Completed:**  
I have developed the GPIO application for LED, Buzzer and Push button for client side Raspberry Pi 3B+ having Raspbian image .

**Work Submission:**  
You can find my work [here](https://github.com/cu-ecen-aeld/final-project-JayashCUB/tree/master/application).

**DoD Achieved:**  
I am able to read Push button value, turn on/of led and buzzer, meeting the Definition of Done (DoD).


**Video Link:** 
Short [Video](https://drive.google.com/file/d/1DorSik3LY2kflzdMKXuq9tbgsgnfOIPI/view?usp=sharing) showing functionality of LED, Buzzer and Push button.


Screenshot showing the push button working with led (red) :
![Image](https://github.com/JayashCUB/final-project-assignment-Intelligent_Driver_Assistance_and_Parking_System/assets/143919364/3e6bed42-5945-43d6-897d-0e4540b31c07)

Screenshot of terminal showing that button is pushed : 
![Image](https://github.com/JayashCUB/final-project-assignment-Intelligent_Driver_Assistance_and_Parking_System/assets/143919364/a80c707b-cbef-4633-9991-eb0fef48a91a)


**References:**  
- [GPIO Input Output](https://roboticsbackend.com/introduction-to-wiringpi-for-raspberry-pi/)
- [Passive Buzzer with raspberry](https://www.14core.com/wiring-the-passive-active-buzzer-with-raspberry-pi/)
