### ISSUE TITLE
Integrate V4L2 with developed socket server

### ISSUE THREAD

**Issue by aneesh1298** [JayashCUB/final-project-assignment-Intelligent_Driver_Assistance_and_Parking_System#6]
Description:
The goal of this task is to integrate the Video4Linux2 (V4L2) capture functionality with the developed socket server in the Intelligent Driver Assistance and Parking System project. This integration will enable the server to capture frames from a camera source using V4L2 and transmit them to a socket client for further processing or display.

DoD:
      Able to detect and send frames to the socket client.

Blockers:
None

**Comment by charan1811** [comment]
Commit :
792f6eff767fe992936167bf4ad53d8bb88b93c4
Description:
Problems faced:
While trying to capture and send frames in a single thread, there was a massive delay between frame that is to be captured and frame to be sent which was creating problems at the client side.
Resolution:
Added Multi threading capability to server to handle Frame capture and Frame to be sent in two different threads.
Evidence:
https://github.com/cu-ecen-aeld/final-project-charan1811/tree/master/PICTURES
